### ISSUE TITLE
Operator Description

### ISSUE THREAD

**Issue by do168** [livlikwav/UOSSE#1]
<1 . Handling Map Data>
1. 개략 명세 : 이 USE CASE는 Operator가 초기화하며, Operator가  시스템에 MAP Data를 삽입, 수정, 삭제하기 위한 기능을 제공한다.

2. 사건의 흐름 :
-Operator가 고유번호를 입력하면서 시작한다.
시스템은 Operator의 고유번호가 유효한지 검사 후 맞으면 Operator에게 Map Data를 입력하라고 표시한다. Operator는 Map data를 입력 한다. 시스템은 Operater가 다음 사항 중 하나를 선택하도록 한다.
-- Map Data 삽입
-- Map Data 수정
-- Map Data 삭제
Operater가 끝났음을 지시한다. 시스템은 입력한 Map data를 화면에 표시하고 입력이 되었음을 알린다.

2.1 Alternate flow
-만일 고유번호가 틀릴 경우 시스템은 등록 시스템 접근을 허용하지 않는다. 삽입되지 않은 Map Data를 수정이나 삭제하려 하거나, 이미 만들어진 Map Data를 또 만들려고 시도할 경우 시스템은 다른 선택을 지시한다.
  

2.2 Map Data 삽입
- Operator는 일정한 형식에 따라 Map Data를 입력한다. Operater가 삽입을 요청하면 시스템은
--삽입한 데이터의 형식을 확인한다.
-- 입력받은 Map Data를 저장한다.
--Alternate flow
----삽입을 위해넣은 Map Data의 형식이 다른 경우 시스템은 오류를 표시하고 재입력을 지시한다.

2.3 Map Data 수정
-시스템이 삽입된 Map Data를 표시한다. Operator는 삽입한 Map Data에서 수정할 부분을 찾아 입력한다.  학생이 수정을 요청하면 시스템은
--수정한 데이터의 형식을 확인한다.
--수정한 Map Data를 저장한다
--Alternate flow
----수정을 위해 넣은 Map Data의 형식이 다른 경우 시스템은 오류를 표시하고 재입력을 지시한다.

2.4 Map Data 삭제
- Operator가 삽입한 Map Data를 지울 것을 지시한다.  시스템은 저장된 Map Data를 지우고 Operator에게 요청이 처리되었음을 알린다.

<2.Set System to Move Robot>
1. 개략 명세 : 이 USE CASE는 Operator가 초기화하며, Operator가  시스템에게 저장된 Map Data로 SIM과의 통신을 통해 로봇을 움직이게 하기 위한 기능을 제공한다.

2. 사건의 흐름 :
-Operator가 고유번호를 입력하면서 시작한다.
시스템은 Operator의 고유번호가 유효한지 검사 후 맞으면 Operator에게 유효하다고 알린다. Operator는 시스템 작동을 지시한다.
2.1 Alternate flow
-만일 고유번호가 틀릴 경우 시스템은 작동 시스템 접근을 허용하지 않는다.

2.2 선조건
-"Handling Map Data" Use Case는 이 Use Case 실행 전에 실행되어야 한다.

**Comment by livlikwav** [comment]
UML 파일에 반영함
+ 수정됨
