### ISSUE TITLE
HGM-UseCase의 시나리오 생각

### ISSUE THREAD

**Issue by livlikwav** [livlikwav/UOSSE#10]
Read Hazard Sensor
Read Color Blob Sensor
Read Current Position
할때마다 경로 재설정하는건 비효율적이지 않나?

그냥 RunRobotSearching에
0과 1을 가지는 Flag (Bool)을 두고
Read 한번 할때마다 변화가 있으면

맵의 변화가 있음을 
로봇 움직임을 담당하는 클래스에 기록을 해서

다음 loop때 있으면 다시 경로 설정하도록 해야겠지?

**Comment by livlikwav** [comment]
UseCaseDiagram을 변경하지 않고

Use Case 명세랑 시나리오를 이런식으로 작성해야할듯?

Read 3개는
단순히 센서값이 존재하면 
-값을 입력하고
-로봇 이동 현황 나타내는 entity의 flag 수정해주고

로봇 이동 현황에 
option이 생겨서
loop{
    if option true : repath
    move by path
}

**Comment by do168** [comment]
해결완료
