### ISSUE TITLE
내꺼 수정할 거

### ISSUE THREAD

**Issue by livlikwav** [livlikwav/UOSSE#16]
- 내 부분 0-8로 되어있는거 0-7로 하기
> GoStep 아예 바꾸면서 수정완료
- GoStep 수정
> 완료
- Colorblob 겹치게 그리도록 수정하기
> 완료. ROBOTONCLRB

- 우찬꺼 Sim 다른 클래스로 빼기?
- 도는거 이미지 명확하게 바꾸기
> 완료

**Comment by livlikwav** [comment]
https://javacan.tistory.com/entry/124

img 변환하기

**Comment by do168** [comment]
2칸 갔을때를 대비해서 empty도 만들어주세요~
= setMapPoint(EMPTY) 만듬

**Comment by livlikwav** [comment]
- 탐색지점 도착하면 색 바뀌기
- 탐색지점 이미지를 깃발로 바뀐다
- 마리오가 EMPTY위에 있게 그린다

**Comment by livlikwav** [comment]
### 이미지 깃발로 수정
IMG파일을 수정하고

### 탐색지점 지나가고 나면
로봇이 GOAL 위에 가서 지나가면
그대로 GOAL로 놔둠.
> 분기문 너무 많아져서 어려워짐 ㅠㅠ

### 마리오가 EMPTY위에 있게 
> 그렇게 하게 수정함

**Comment by livlikwav** [comment]
GOAL을 다시 지나가는지
ROBOTONGOAL을 다시 지나가는지 모르겠는데
그럼 지워짐 EMPTY로 ㅎㅎ 
일단 이건 욕심

**Comment by livlikwav** [comment]
191202 1129
1. setMapPoint 모든 종류 점 다 가능하게 해두기
2. doOperation 분기문 개선 방향 잡음!

개념적인 포인트
START
로봇
ROBOT
밟을 수 있는 포인트
SEENCOLORBLOB , GOAL, EMPTY, FINISHEDGOAL
밟을 수 없는 포인트
HAZARD
GUI측면의 포인트
센서로 부터~ SEEN, NEW/ CLRB, HZD
밟을 수 있는 으로 부터~ROBOTONCLRB, ONGOAL, ONFNGOAL
밟고나서 ~ FINISHEDGOAL

EMPTY
ROBOT
GOAL
SEENHAZARD
SEENCOLORBLOB
NEWHAZARD
NEWCOLORBLOB
ROBOTONGOAL
ROBOTONCLRB
FINISHEDGOAL
ROBOTONFNGOAL

**Comment by livlikwav** [comment]
# 다 완료
