### ISSUE TITLE
우찬 수정할거

### ISSUE THREAD

**Issue by livlikwav** [livlikwav/UOSSE#17]
# 클래스 다이어그램 수정 계획
![image](https://user-images.githubusercontent.com/44190293/70050513-7d8f7f00-1612-11ea-90b8-e4dd850bcfbf.png)

RobotOperationManager
> control

RobotOperation 
> entity

# 도우찬 할일
1. 클래스 다이어그램 부터 수정
2. 코드 객체 지향적으로 수정. 내부 변수 다 private하게
3. 순차도 다 수정
4. 시나리오도는 놔두되, hazard 같은 이름들만 빼기
5. 순차도에 맞춰 클래스도 수정

# 하경민 할일
~~0. mapGUIForm 클래스 다이어그램 보내주기~~
1. 객체상태도 그리기
2. 컴포넌트도 공부
3. 배치도 공부~

**Comment by livlikwav** [comment]
회전할때 thread sleep 넣어야함
움직일때 한번에 그려짐

**Comment by livlikwav** [comment]
마지막에 끝내는 Step때
실제위치로 다시 그려줘야함
안 움직인채로 끝나버림

**Comment by livlikwav** [comment]
![mapGUIForm_java](https://user-images.githubusercontent.com/44190293/70052668-2344ed00-1617-11ea-9460-385f851ea844.png)

**Comment by livlikwav** [comment]
우찬 MapGUIForm 수정한거
니꺼에 올려둬야함
수정한 파일
java랑 txt 둘다

**Comment by livlikwav** [comment]
![image](https://user-images.githubusercontent.com/44190293/70072024-8e072000-1639-11ea-8c1f-229e30c95b07.png)

**Comment by livlikwav** [comment]
# 내일 코드를 같이 Pair Programming으로 같이 UML 짜버리기 빠르게

# 그 이후에 상태 전이도 내가 그릴테니 옆에서 질문하면서 바로 그리기

**Comment by do168** [comment]
MapDataManager랑 MapInputDataForm이랑 Map 객체를 통해 get set 하기

**Comment by do168** [comment]
RobotOperationManager 의 상태
1. 지도 정보 입력
 [플래그 검사]
2. 경로 계산

**Comment by livlikwav** [comment]
# 우찬 수정할거 1205 마프설시간

## InputMapDataForm에서 초기화하지 않고 MapDataManager가 초기화

**Comment by livlikwav** [comment]
![image](https://user-images.githubusercontent.com/44190293/70231062-f7537400-179c-11ea-9613-ebf38b5990cb.png)
