### ISSUE TITLE
Move Robot 유스케이스 이름에 대해

### ISSUE THREAD

**Issue by do168** [livlikwav/UOSSE#7]
시나리오를 적는 과정에서 유스케이스 이름을 적을 때 Move Robot를 해석하는데 뜻은 알겠는데 글로 표현을 못해서 일단 서로 이해했던 ADD-ON 시스템 작동 (Run ADD-ON System)이라 적었고 내일 이거 표현을 어떻게 해야할지 요청.

**Comment by do168** [comment]
아, 합치는 건 내일 같이 하는걸로 . 서로 헷갈릴거같다. 머 바꿨는지 말하면서 바꾸자

**Comment by livlikwav** [comment]
ㅇㅇㅇ 바꿧다
